name: Publish to nuget.org

on:
  - workflow_dispatch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
      - name: Pack
        run: dotnet pack --no-build -c Release -o .
      - name: Publish
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source nuget.org --skip-duplicate
